version: '3.3'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    image: spring-mvc-war
    container_name: spring-mvc-war   
    expose:
        - 8080
    ports:
      - 9999:8080