version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: spring-mvc-war
    expose: 
      - 8080

  loadbalancer:
    container_name: nginx2
    image: nginx:1.13
    expose: 
      - 80
    ports:
      - 8003:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on: 
      - app
  
